server:
  port: 8086

spring:
  application:
    name: notification-service
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27018}
      database: ${SPRING_DATA_MONGODB_DATABASE:notificationdb}
      username: ${SPRING_DATA_MONGODB_USERNAME:notification_user}
      password: ${SPRING_DATA_MONGODB_PASSWORD:notification_password}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:notificationdb}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  graphql:
    graphiql:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

grpc:
  clients:
    patient-target: ${PATIENT_GRPC_TARGET:localhost:9093}
    physician-target: ${PHYSICIAN_GRPC_TARGET:localhost:9092}
