server:
  port: 8086

spring:
  application:
    name: notification-service
  mongodb:
    host: ${SPRING_MONGODB_HOST:notification-db}
    port: ${SPRING_MONGODB_PORT:27017}
    database: ${SPRING_MONGODB_DATABASE:notificationdb}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
  graphql:
    graphiql:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

grpc:
  clients:
    patient-service-id: ${PATIENT_GRPC_SERVICE_ID:patient-service}
    patient-port: ${PATIENT_GRPC_PORT:9093}
    physician-service-id: ${PHYSICIAN_GRPC_SERVICE_ID:physician-service}
    physician-port: ${PHYSICIAN_GRPC_PORT:9092}
