server:
  port: 8081

spring:
  application:
    name: tenant-service
  mongodb:
    host: ${SPRING_MONGODB_HOST:tenant-db}
    port: ${SPRING_MONGODB_PORT:27017}
    database: ${SPRING_MONGODB_DATABASE:tenantdb}
  graphql:
    graphiql:
      enabled: true

grpc:
  clients:
    patient-service-id: ${PATIENT_GRPC_SERVICE_ID:patient-service}
    patient-port: ${PATIENT_GRPC_PORT:9093}
    physician-service-id: ${PHYSICIAN_GRPC_SERVICE_ID:physician-service}
    physician-port: ${PHYSICIAN_GRPC_PORT:9092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
